-- AlterTable
ALTER TABLE "RefreshToken" ADD COLUMN IF NOT EXISTS "deviceName" TEXT;
ALTER TABLE "RefreshToken" ADD COLUMN IF NOT EXISTS "lastUsedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "RefreshToken" ADD COLUMN IF NOT EXISTS "platform" TEXT;
